export const words_and_hints = {
    "Afghanistan" : "the capital of this country is Kabul",
    "Albania" : "the capital of this country is Tirana",
    "Algeria" : "the capital of this country is Algiers",
    "Andorra" : "the capital of this country is Andorra la Vella",
    "Angola" : "the capital of this country is Luanda",
    "Argentina" : "the capital of this country is Buenos Aires",
    "Armenia" : "the capital of this country is Yerevan",
    "Australia" : "the capital of this country is Canberra",
    "Austria" : "the capital of this country is Vienna",
    "Azerbaijan" : "the capital of this country is Baku",
    "Bahrain" : "the capital of this country is Manama",
    "Bangladesh" : "the capital of this country is Dhaka",
    "Barbados" : "the capital of this country is Bridgetown",
    "Belarus" : "the capital of this country is Minsk",
    "Belgium" : "the capital of this country is Brussels",
    "Belize" : "the capital of this country is Belmopan",
    "Benin" : "the capital of this country is Porto-Novo",
    "Bhutan" : "the capital of this country is Thimphu",
    "Bolivia" : "the capital of this country is La Paz, Sucre",
    "Botswana" : "the capital of this country is Gaborone",
    "Brazil" : "the capital of this country is Brasilia",
    "Brunei" : "the capital of this country is Bandar Seri Begawan",
    "Bulgaria" : "the capital of this country is Sofia",
    "Burundi" : "the capital of this country is Bujumbura",
    "Cambodia" : "the capital of this country is Phnom Penh",
    "Cameroon" : "the capital of this country is Yaounde",
    "Canada" : "the capital of this country is Ottawa",
    "Chad" : "the capital of this country is N’Djamena",
    "Chile" : "the capital of this country is Santiago",
    "China" : "the capital of this country is Beijing",
    "Colombia" : "the capital of this country is Bogota",
    "Comoros" : "the capital of this country is Moroni",
    "Croatia" : "the capital of this country is Zagreb",
    "Cuba" : "the capital of this country is Havana",
    "Cyprus" : "the capital of this country is Nicosia",
    "Denmark" : "the capital of this country is Copenhagen",
    "Djibouti" : "the capital of this country is Djibouti",
    "Dominica" : "the capital of this country is Roseau",
    "Ecuador" : "the capital of this country is Quito",
    "Egypt" : "the capital of this country is Cairo",
    "Eritrea" : "the capital of this country is Asmara",
    "Estonia" : "the capital of this country is Tallinn",
    "Ethiopia" : "the capital of this country is Addis Ababa",
    "Fiji" : "the capital of this country is Suva",
    "Finland" : "the capital of this country is Helsinki",
    "France" : "the capital of this country is Paris",
    "Gabon" : "the capital of this country is Libreville",
    "Georgia" : "the capital of this country is Tbilisi",
    "Germany" : "the capital of this country is Berlin",
    "Ghana" : "the capital of this country is Accra",
    "Greece" : "the capital of this country is Athens",
    "Grenada" : "the capital of this country is Saint George’s",
    "Guatemala" : "the capital of this country is Guatemala City",
    "Guinea" : "the capital of this country is Conakry",
    "Guyana" : "the capital of this country is Georgetown",
    "Haiti" : "the capital of this country is Port-au-Prince",
    "Honduras" : "the capital of this country is Tegucigalpa",
    "Hungary" : "Bthe capital of this country is udapest",
    "Iceland" : "the capital of this country is Reykjavik",
    "India" : "the capital of this country is New Delhi",
    "Indonesia" : "the capital of this country is Jakarta",
    "Iran" : "the capital of this country is Tehran",
    "Iraq" : "the capital of this country is Baghdad",
    "Ireland" : "the capital of this country is Dublin",
    "Palestine" : "the capital of this country is Jerusalem",
    "Italy" : "the capital of this country is Rome",
    "Jamaica" : "the capital of this country is Kingston",
    "Japan" : "the capital of this country is Tokyo",
    "Jordan" : "the capital of this country is Amman",
    "Kazakhstan" : "the capital of this country is Astana",
    "Kenya" : "the capital of this country is Nairobi",
    "Kiribati" : "the capital of this country is Tarawa Atoll",
    "Kosovo" : "the capital of this country is Pristina",
    "Kuwait" : "the capital of this country is Kuwait City",
    "Kyrgyzstan" : "the capital of this country is Bishkek",
    "Laos" : "the capital of this country is Vientiane",
    "Latvia" : "the capital of this country is Riga",
    "Lebanon" : "the capital of this country is Beirut",
    "Lesotho" : "the capital of this country is Maseru",
    "Liberia" : "the capital of this country is Monrovia",
    "Libya" : "the capital of this country is Tripoli",
    "Liechtenstein" : "the capital of this country is Vaduz",
    "Lithuania" : "the capital of this country is Vilnius",
    "Luxembourg" : "the capital of this country is Luxembourg",
    "Macedonia" : "the capital of this country is Skopje",
    "Madagascar" : "the capital of this country is Antananarivo",
    "Malawi" : "the capital of this country is Lilongwe",
    "Malaysia" : "the capital of this country is Kuala Lumpur",
    "Maldives" : "the capital of this country is Male",
    "Mali" : "the capital of this country is Bamako",
    "Malta" : "the capital of this country is Valletta",
    "Mauritania" : "the capital of this country is Nouakchott",
    "Mauritius" : "the capital of this country is Port Louis",
    "Mexico" : "the capital of this country is Mexico City",
    "Moldova" : "the capital of this country is Chisinau",
    "Monaco" : "the capital of this country is Monaco",
    "Mongolia" : "the capital of this country is Ulaanbaatar",
    "Montenegro" : "the capital of this country is Podgorica",
    "Morocco" : "the capital of this country is Rabat",
    "Mozambique" : "the capital of this country is Maputo",
    "Myanmar" : "the capital of this country is Naypyidaw",
    "Namibia" : "the capital of this country is Windhoek",
    "Nauru" : "the capital of this country is Yaren District",
    "Nepal" : "the capital of this country is Kathmandu",
    "Netherlands" : "the capital of this country is Amsterdam",
    "Nicaragua" : "the capital of this country is Managua",
    "Niger" : "the capital of this country is Niamey",
    "Nigeria" : "the capital of this country is Abuja",
    "Norway" : "the capital of this country is Oslo",
    "Oman" : "the capital of this country is Muscat",
    "Pakistan" : "the capital of this country is Islamabad",
    "Palau" : "the capital of this country is Melekeok",
    "Panama" : "the capital of this country is Panama City",
    "Paraguay" : "the capital of this country is Asuncion",
    "Peru" : "the capital of this country is Lima",
    "Philippines" : "the capital of this country is Manila",
    "Poland" : "the capital of this country is Warsaw",
    "Portugal" : "the capital of this country is Lisbon",
    "Qatar" : "the capital of this country is Doha",
    "Romania" : "the capital of this country is Bucharest",
    "Russia" : "the capital of this country is Moscow",
    "Rwanda" : "the capital of this country is Kigali",
    "Samoa" : "the capital of this country is Apia",
    "Senegal" : "the capital of this country is Dakar",
    "Serbia" : "the capital of this country is Belgrade",
    "Seychelles" : "the capital of this country is Victoria",
    "Singapore" : "the capital of this country is Singapore",
    "Slovakia" : "the capital of this country is Bratislava",
    "Slovenia" : "the capital of this country is Ljubljana",
    "Somalia" : "the capital of this country is Mogadishu",
    "Spain" : "the capital of this country is Madrid",
    "Sudan" : "the capital of this country is Khartoum",
    "Suriname" : "the capital of this country is Paramaribo",
    "Swaziland" : "the capital of this country is Mbabane",
    "Sweden" : "the capital of this country is Stockholm",
    "Switzerland" : "the capital of this country is Bern",
    "Syria" : "the capital of this country is Damascus",
    "Taiwan" : "the capital of this country is Taipei",
    "Tajikistan" : "the capital of this country is Dushanbe",
    "Tanzania" : "the capital of this country is Dodoma",
    "Thailand" : "the capital of this country is Bangkok",
    "Togo" : "the capital of this country is Lome",
    "Tonga" : "the capital of this country is Nuku’alofa",
    "Tunisia" : "the capital of this country is Tunis",
    "Turkey" : "the capital of this country is Ankara",
    "Turkmenistan" : "the capital of this country is shgabat",
    "Tuvalu" : "the capital of this country is Funafuti",
    "Uganda" : "the capital of this country is Kampala",
    "Ukraine" : "the capital of this country is Kyiv",
    "Uruguay" : "the capital of this country is Montevideo",
    "Uzbekistan" : "the capital of this country is Tashkent",
    "Venezuela" : "the capital of this country is Caracas",
    "Vietnam" : "the capital of this country is Hanoi",
    "Yemen" : "the capital of this country is Sanaa",
    "Zambia" : "the capital of this country is Lusaka",
    "Zimbabwe" : "the capital of this country is Harare",
    //End of countries zone.
    "addition": "The process of adding numbers",
    "meeting": "Event in which people come together",
    "number": "Math symbol used for counting",
    "exchange": "The act of trading",
    "canvas": "Piece of fabric for oil painting",
    "garden": "Space for planting flower and plant",
    "position": "Location of someone or something",
    "feather": "Hair like outer covering of bird",
    "comfort": "A pleasant feeling of relaxation",
    "tongue": "The muscular organ of mouth",
    "expansion": "The process of increase or grow",
    "country": "A politically identified region",
    "group": "A number of objects or persons",
    "taste": "Ability of tongue to detect flavour",
    "store": "Large shop where goods are traded",
    "field": "Area of land for farming activities",
    "friend": "Person other than a family member",
    "pocket": "A bag for carrying small items",
    "needle": "A thin and sharp metal pin",
    "expert": "Person with extensive knowledge",
    "statement": "A declaration of something",
    "second": "One-sixtieth of a minute",
    "library": "Place containing collection of books"
    }

    export const words = Object.keys(words_and_hints)
    export const hints = Object.values(words_and_hints)